### ISSUE TITLE
Estimates of needed capabilities for strong lensing cosmography in the LSST era

### ISSUE THREAD

**Issue by drphilmarshall** [wadawson/Enabling-LSST-Dark-Energy-Science#1]
@wadawson @cmccully

Dear Eric, Curtis, Will, Veronica and Adam,

I made a small start on the strong lensing contribution to the Dark Energy part of the community study on "Maximizing Science in the Era of LSST: A Community-based Study of Needed US OIR Capabilities" (that we all registered our interest in a while back). See what you think! I laid out some subsections, attempted a preamble to each, and suggested which parts you might be most interested in working on. If you are agreeable, we could get to work on our first task with this subdivision of labor! 

As @janewman-pitt-edu says:

> For each science area, we should:
> 
> 1) Describe the science need in a few sentences at most
> 
> 2) Describe the needed capability (or capabilities) in enough detail that someone could determine > whether they overlap with other needs. (E.g.:  “medium-resolution (R~4000-6000) spectroscopy covering the full optical window for i<25.3 objects with multiplexing of ~1000 over ~10 arcminute diameter fields” could work, or for a different case “optical medium-resolution spectroscopy with a highly-multiplexed spectrograph with a many-degree FoV on a 4m telescope” would also give enough information to allow identification of common needs).

So we should keep this _very brief_ and as high level as he says. What do you think? Here's my suggestion for dividing up the work:
- [x] Time Delay and Compound Lens Cosmography: High Precision Galaxy Mass Models from High Resolution Imaging and Spectroscopy:  Phil Marshall, Adam Bolton and others
- [x] Time Delay Cosmography: Additional Monitoring to Improve Time Delay Accuracy: Eric Linder, Phil Marshall and others
- [x] Time Delay Cosmography: Multi-object Spectroscopy to Improve the Fidelity of our Lens Environment and Line of Sight Characterization: Curtis McCully, Adam Bolton, Phil Marshall and others
- [x] Cluster Mass Function: Spectroscopic Surveying in Cluster Fields: Will Dawson and others

The idea is that the first author would go first, and then pass on to the second for light revision and discussion. Jeff's goal is for us to complete this first pass by March 28, or in other words, the end of tis week!

**Comment by drphilmarshall** [comment]
PS. I think Veronica Motta might like to help with the clusters piece too!

**Comment by janewman-pitt-edu** [comment]
Note that we're supposed to get things down to ~1-3 items from cosmic
frontiers total, ideally, so we really don't want to get too in depth right
now. On 3/28 we'll look into synergies between the different areas.

Best,

Jeff

**Comment by drphilmarshall** [comment]
Yes: we'll go for very high level, off the cuff estimates at this point. Thanks Jeff!

**Comment by drphilmarshall** [comment]
More guidance from Jeff:

> For the ~half-dozen science cases that end up being focused on in the study, we'll ultimately be asked to quantify the gain/loss from a particular capability being present/absent to justify its importance, if possible.  I don't expect we're equipped to do that now in most cases, but if there are capabilities you're looking at that obviously have greater or lesser impact on cosmological constraining power, it would be useful to know that (i.e., we don't want to spend substantial time on niche cases).
> 
> A particular question we've been asked to keep in mind is whether any of our science cases synergize with the recommendations from the Elmegreen report:
> - wide-field multiplexed spectroscopy on a medium- to large-aperture telescope
> - high throughput, moderate resolution spectrograph on Gemini South to support faint-object spectroscopy
> - an OIR transient follow up system fed by event brokers
> - US involvement in GSMT(s)

This is important: the high resolution spectro-imaging is crucial to the strong lens cosmography. Additional monitoring and field spectroscopy is less important, I'd say. I'll call out the GSMT's (currently referred to as "ELT's") in that subsection.

**Comment by wadawson** [comment]
I added a number of cluster spectroscopic science measurements to sl.tex with commit 6b198e6. Note that only one of these actually deals with the subject of strong lensing in the cluster environment. The others are more generally related to "Cluster Mass Function: Spectroscopic Surveying in Cluster Fields". We can move some of this text as the report develops.

**Comment by drphilmarshall** [comment]
Sweet, thanks Will! @evlinder reports that he will join this effort after this week, and Adam tells me he will make a GitHub account and join us after he has sorted out his movers. I don't think we'll have too much to say in the additional monitoring section, but there could be more in the environment piece, because there's some synergies with other spectroscopic surveys that could come out.

**Comment by drphilmarshall** [comment]
Hi @cmccully - will you have time to add some notes on observations needed for environment/line of sight characterization today? Also, I just added some notes on additional monitoring, which I think you should read and correct - you've thought about this a lot more than I have. Thanks!

**Comment by drphilmarshall** [comment]
Hi all,

After meeting with the rest of the "Maximizing Science in the Era of LSST" dark energy study group today, I added some numbers from Meng et al 2015 to the follow up high resolution imaging subsection, and wrote some very brief notes on the environment/line of sight characterization subsection.
- @tommasotreu Would you mind taking a look at the content of [`sl.tex`](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/sl.tex#L26) and giving me some feedback, please? The hyperlink in the previous sentence will take you straight to the right line. In particular, anything we can say about the time delay lens cosmography IFU requirements on future facilities would be most helpful. For background, this repo has [a nice README](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/README.md). Thanks! 
- @cmccully I went ahead and wrote some notes on what I think we will need to do well at environment/line of sight structure characterization [in the same file, further down](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/sl.tex#L95). What do you think needs adding, if anything, given our charge?  You might also take a look at [the "additional monitoring" subsection](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/sl.tex#L69) too, if you have time. Thanks!
- @janewman-pitt-edu Is there anything else you need in terms of specifics? 

Thanks very much, all!

Phil

**Comment by janewman-pitt-edu** [comment]
It'd be preferable to be able to say something about wavelength range and resolution requirements (wavelength must be IR for AO; resolution I presume needs to be enough to get the velocity dispersions, so R>~ a few thousand I guess?  Unless we anticipate getting the dispersion from separate optical spectroscopy?)

**Comment by tommasotreu** [comment]
For time delay cosmography, will need capabilities such as those currently available on Keck and that will be available on TMT. More precisely: first you need optical spectroscopy to get redshifts of deflector and source, pretty much any resolution, the wider wavelength range the better, so something like 3500-10,000AA and maybe a triplespec covering JHK in the IR. After the redshift is known AO assisted integral field spectroscopy would be best, something like 4"x4" with R~4000-5000 in the near IR. Wavelength range 1-2.2 microns (CaT at 8800-9000A, or CO at 1.5-1.6micron rest frame). IRIS on TMT would provide this capability (OSIRIS is the current best option, even though the field of view is a bit too small and the current AO system at Keck has relatively low strehl at 1mu. Working on improving that; TMT should be much better).

**Comment by drphilmarshall** [comment]
Thanks Tommaso! I folded in your comments to [`sl.tex`](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/blob/master/sl.tex#L26), please let me know if you see anything that needs fixing.

**Comment by janewman-pitt-edu** [comment]
Thanks, Tommaso, that�s exactly the sort of thing we need.

Best,

Jeff

**Comment by evlinder** [comment]
Hi Tommaso,

I know you're on TMT, but doesn't GMT also plan to have acceptable AO?
Also, I thought it's spatial resolution will be a bit better (more compact
design?)?

Best,
Eric

**Comment by cmccully** [comment]
Hi Phil,
I will take a look at the lens environment section and make a pull request. I think that we can do a lot of the environment modeling with existing LSST data and/or in coordinatation with the Weak lensing and Photo-z groups. I think we are also well matched to the DESI instrument so there should be an opportunity for overlap. 
Curtis

**Comment by MEDickinson** [comment]
Dear Eric -

TMT, GMT, and E-ELT are all interesting here.  All three plan to have AO-fed near-IR imagers and IFUs as first- or early-light instruments (TMT: IRIS;  GMT: GMTIFs;  EELT: ELT-CAM and ELT-IFU) with somewhat different capabilities.  To first order, diffraction-limited angular resolution scales inversely with aperture diameter, so E-ELT (39m) will be have the best resolution, TMT (30m) next, then GMT (~24m).

```
Yours,

    Mark
```

> On  29 Mar 2016, at 9:43 PM, evlinder notifications@github.com wrote:
> 
> Hi Tommaso,
> 
> I know you're on TMT, but doesn't GMT also plan to have acceptable AO?
> Also, I thought it's spatial resolution will be a bit better (more compact
> design?)?
> 
> Best,
> Eric
> 
> On Tue, Mar 29, 2016 at 12:55 PM, Tommaso Treu notifications@github.com
> wrote:
> 
> > For time delay cosmography, will need capabilities such as those currently
> > available on Keck and that will be available on TMT. More precisely: first
> > you need optical spectroscopy to get redshifts of deflector and source,
> > pretty much any resolution, the wider wavelength range the better, so
> > something like 3500-10,000AA and maybe a triplespec covering JHK in the IR.
> > After the redshift is known AO assisted integral field spectroscopy would
> > be best, something like 4"x4" with R~4000-5000 in the near IR. Wavelength
> > range 1-2.2 microns (CaT at 8800-9000A, or CO at 1.5-1.6micron rest frame).
> > IRIS on TMT would provide this capability (OSIRIS is the current best
> > option, even though the field of view is a bit too small and the current AO
> > system at Keck has relatively low strehl at 1mu. Working on improving that;
> > TMT should be much better).
> > 
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/issues/1#issuecomment-202996644
> > 
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/issues/1#issuecomment-203068462

---

E-mail: med@noao.edu mailto:med@noao.edu      Telephone:  (+1) 520 318 8531

## Address:    NOAO, 950 N. Cherry Ave., Tucson AZ 85719 USA

**Comment by drphilmarshall** [comment]
Thanks Mark. I believe strong lensing is one of the science drivers (is that the right term, Tommaso?) for TMT, and it's the system we (as a community) understand the best at the moment.  But, it's very possible that, given the broad reach of the LSST DESC SL working group and LSST strong lensing science collaboration, we would indeed end up applying for time at all three facilities. I have tweaked the wording to reflect this, [see what you think](https://github.com/wadawson/Enabling-LSST-Dark-Energy-Science/commit/6a0dd66ab5151aacc54a2e9a9264b58b74d28976).

**Comment by drphilmarshall** [comment]
Thanks for the PR, @cmccully! Does anything need doing with the additional monitoring subsection, in your opinion?

**Comment by drphilmarshall** [comment]
Closing this out so we can focus on polishing the refactored paper - thanks for all your help, everyone!
