### ISSUE TITLE
questions on short strong lensing session

### ISSUE THREAD

**Issue by janewman-pitt-edu** [wadawson/Enabling-LSST-Dark-Energy-Science#18]
@drphilmarshall  : I did some trimming and editing on the strong lensing in photoz_short.tex .  A couple of questions:

1) for the spectroscopy for characterizing the general effects of weak lensing on strong lensing measurements:  is this supposed to be in the same fields as the strong lens systems, or can it be done anywhere?  Only in the latter case can it have synergies with training surveys.

2) Are you OK with the alterations I made?  I don't think it's actually feasible to embed strong lenses in the photo-z training surveys, as that would bias redshift distributions (e.g. weight us towards having overdensities at z~0.4).

**Comment by drphilmarshall** [comment]
Thanks Jeff - all your edits look good to me. It'd be a shame if we can't combine the SL fields with the photo-z work, but I see the problem. Synergy with DESI is still a possibility I think. The answer to your Q1 is yes, BTW - so your text looks good. Thanks!
