### ISSUE TITLE
Should we have a separate CL section?

### ISSUE THREAD

**Issue by drphilmarshall** [wadawson/Enabling-LSST-Dark-Energy-Science#4]
@janewman-pitt-edu @wadawson What do you think? The cluster mass function part does not seem to fit all that well with the rest of the SL section.

**Comment by janewman-pitt-edu** [comment]
I agree that makes sense.  Are you willing to take charge of that section, Anja?

jeff

**Comment by janewman-pitt-edu** [comment]
Yep, I'm on it! Apologies for being offline last week; will be back with Internet from this afternoon / tomorrow.
Will, my git ID is anjavdl. Can you please give me access to the repository?

Anja

**Comment by wadawson** [comment]
Anja,

I just added you. Sorry for the delay. Since the repo is open hopefully you weren't delayed. 

Will

## 

Please forgive the brevity; sent from my phone.
