### ISSUE TITLE
Completeness

### ISSUE THREAD

**Issue by drphilmarshall** [wadawson/Enabling-LSST-Dark-Energy-Science#6]
Hi @janewman-pitt-edu 

What's the guidance we've been given on the scale and scope of our report, in terms of the number of science cases presented? I could imagine there being some desire to make the comparison between science cases across the whole LSST science community as easy as possible, at least at first - but I also would have thought that tracking all science cases that have key dependencies on follow-up data would be important. Should we aim for high completeness in the dark energy science report, or do we need to down-select?

**Comment by janewman-pitt-edu** [comment]
Hi Phil,

The goal for the final product is not to make a comprehensive set of science cases but rather to make a limited number (numbers like 6 or 8 have been discussed) of science cases in some detail that strongly justify particular capabilities as needed for LSST to enable Decadal survey-relevant science (the Matheson white paper was more in the comprehensive-set direction and didn't get as much traction as one might like).  That's a major reason I've tried to avoid asking people for too much text till we know what areas we as a group will be asked to push forward, I don't want to waste peoples' time.  However, brainstorming etc. is still valuable - I'd anticipate that even if the detailed justification is presented for only one science case for a particular capability, there'd be some sort of paragraph or so saying that that capability would also be great for X, Y, and Z reasons.  I also think that when there are many dark energy cases pointing towards the same capability, that could all be folded into one of those big science cases (e.g. photo-z training, intrinsic alignment studies, and some of the cluster science discussed have similar instrumental demands and I expect could be folded together into one case).

I've copied Joan Najita and Beth Willman who can help to clear things up if what I am saying is inaccurate, though.

Best,

Jeff

**Comment by drphilmarshall** [comment]
Got it. Would it help if we made a table of all our subsections (one per row) and populated it with various technical capabilities? I guess it'd be fastest to do this in a shared Google sheet, and then take a screenshot for the report when we're ready. Maybe you and @bethwillman have already thought about what the columns of this table should be?

**Comment by janewman-pitt-edu** [comment]
Hi Phil,

I'm CC'ing Beth and Joan in case they have thoughts on that idea.  My first thought would be that that is basically the big table from the Matheson white paper once you put everyone together, so possibly redundant.

Best,

Jeff

**Comment by janewman-pitt-edu** [comment]
Dear Phil and Jeff, 

Jeff's description is correct! We are aiming to identify high priority capabilities needed for LSST-enabled science and to illustrate the critical need for these with a limited set of examples of the quantitative flowdown from science to capabilities. 

In the end it should be clear not only (i) why the capability is needed but also (ii) what exactly is needed. e.g., if it's spectroscopy, how many sources at what magnitude to what s/n, at what resolution, wavelength coverage, multiplexing�and corresponding constraint on telescope aperture. The last part is missing from the Elmegreen report, so it is highly desired as the next step. 

You might choose to work out a science case that has a combination of strong synergy with NWNH and strongest demands on capabilities. Identifying other science cases that need the same capabilities would strengthen the argument (echoing what Jeff said). 

Please feel free to update the Matheson table with your group's views. 

Many thanks for your effort!
Joan
