### ISSUE TITLE
Redshift space distortion constraints of modified gravity

### ISSUE THREAD

**Issue by wadawson** [wadawson/Enabling-LSST-Dark-Energy-Science#9]
@EliseJ ,
In today's telecon @anjavdl mentioned that you might be able to say something about redshift space distortion constraints on modified gravity. Would you mind contributing some text in the cluster section regarding redshift space distortion?
Thank you.

**Comment by EliseJ** [comment]
Hi Will,

Sorry for the delay in repying. I'll add some text one this asap!

Thanks,
Elise

**Comment by EliseJ** [comment]
Hi Will,

I added some text on RSD, lensing profiles and infall kinematics in the context of clusters and modified gravity. The discussion is very general so please feel free to edit or comment out anything you do not think is relevant.

Elise

**Comment by janewman-pitt-edu** [comment]
Hi Elise,

Can you check out the attached page?  Some characters got mangled when you pasted into the Latex document and I want to make sure I inserted correct substitutions.

Best,

Jeff

**Comment by EliseJ** [comment]
Hi Jeff,

Sorry about that, I should have checked it would compile. It looks fine now I think.

Best wishes,
Elise

**Comment by rmandelb** [comment]
The latest version of the doc still doesn't compile, Jeff.  Is it possible your changes didn't get pushed?  I can edit the clusters section but didn't want to cause conflicts if you've already done it and later push your edits.

**Comment by drphilmarshall** [comment]
The paper now compiles, so I think we can close this!

**Comment by janewman-pitt-edu** [comment]
Hi Elise,

A heads-up that I�m commenting out a lot of the modified gravity text for the moment, as based on your text it�s hard to argue for a specific observational complement to LSST, apart from the cluster infall work.  However, I think there�s a particular case where talking about redshift-space distortions in surveys could make sense: if there�s information to be gained by doing this _in the same parts of the sky_ as the weak lensing measurements, we should be explicit about that.  Otherwise, the RSD measurements could be dominated by DESI in the North, while the lensing primarily comes from LSST in the south.

Best,

Jeff

**Comment by EliseJ** [comment]
Hi Jeff,

OK. I think there is a case to be made for figure of merit improvements by
having
weak gravitational lensing from a survey with photometric redshifts and
galaxy clustering and redshift space distortions from a survey with
spectroscopic redshifts. Should I add some text to the cluster section to
support this?

Elise

**Comment by janewman-pitt-edu** [comment]
Hi Elise,

I had in mind whether there are any gains like that for modified gravity tests in particular (to go with the theme).  We could certainly add something like that as an additional support for the photo-z calibration spectroscopy, though.  It’s hard to know which prediction for the figure of merit gain to trust though :)

Best,

Jeff

**Comment by EliseJ** [comment]
Hi Jeff,

I had in mind the results from Kirk et al 2015 where they show results for
modified gravity.
I agree there seems to be a lot of conflicting reports of the increase in
the figure of merit  for this when considering Gaztanaga et al
predictions.

Best wishes,
Elise

**Comment by janewman-pitt-edu** [comment]
Hi Elise, 

Sure, that’d fit in the modified gravity section then!

jeff
